export const state = {
    allPlots: [],
    allLocals: [],
    allOwners: [],
    allTransactions: [],
    mergedPlots: [],
    streets: [],
    lotterySettings: {},
    lotteryHistory: [],
    eligibleForLottery: [],
    physicalPersons: [],
    nextWinnerIndex: 0,
    currentUser: null,
    modalHistory: [],
    isDragging: false,
    viewBox: { x: 0, y: 0, w: 0, h: 0 },
    initialViewBox: {},
    maxViewboxWidth: 4296,
};
